max_width = 80
# comment_width = 90
# wrap_comments = true
# format_code_in_doc_comments = true
match_arm_leading_pipes = "Preserve"
# reorder_impl_items = true
# group_imports = "StdExternalCrate"
use_field_init_shorthand = true
